include: package:lint/analysis_options.yaml

analyzer:
  errors:
    invalid_assignment: info
    dead_code: error

linter:
  rules:
    prefer_single_quotes: true
    always_require_non_null_named_parameters: true
    avoid_empty_else: true
    avoid_dynamic_calls: false
    avoid_final_parameters: true
    avoid_positional_boolean_parameters: false
    avoid_implementing_value_types: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_setters_without_getters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    use_build_context_synchronously: false
    camel_case_extensions: true
    camel_case_types: true
    comment_references: true
    flutter_style_todos: true

# rules: https://dart-lang.github.io/linter/lints/options/options.html
# customize: https://dart.dev/guides/language/analysis-options#disabling-individual-rules
